local wk = require("which-key")
wk.add({
	{ "<leader>c", group = "Comment" },
	{ "<leader>C", group = "Cargo" },
	{ "<leader>d", group = "Debugger" },
	{ "<leader>h", group = "Git" },
	{ "<leader>ht", group = "Toggle" },
	{ "<leader>f", group = "Find" },
	{ "<leader>l", group = "LaTeX" },
	{ "<leader>r", group = "Remote" },
	{ "<leader>i", group = "LSP" },
	-- { "<leader>r", desc = "Rename Symbol" },
	-- { "<leader>a", desc = "Code Action" },
	{ "gd", desc = "Go to Definition" },
	{ "gD", desc = "Go to Declaration" },
	{ "gI", desc = "Go to Implementation" },
	{ "gr", desc = "Go to Next Reference" },
	{ "<leader>iD", desc = "Type Definition" },
	{ "<leader>is", desc = "Search Document Symbols" },
	{ "<leader>iS", desc = "Search Dynamic Workspace Symbols" },
	{ "<leader>t", group = "Trouble" },
})
